####################################
###  パラメータ設定ファイル            ###
####################################

### カメラ設定
[Param]
sigma = 0.01
data_path = "../data/depth_0025.png"
param_R = 0.02
param_K = 30


[Camera]
fx = 626.074
fy = 625.603
cx = 340.625
cy = 238.199
